name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug
  RUST_BACKTRACE: full

# This creates a sequential queue for 'main' (by having a static group name)
# and cancels in-progress runs for just feature branches/PRs.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  prepare-ci-image:
    uses: dlrobson/toolbox/.github/workflows/prepare-ci-image.yml@main
    permissions:
      packages: write
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}-ci
      dockerfile-context: images/ci/
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  workflow-initialization:
    runs-on: ubuntu-latest
    if: success() || failure()
    needs: prepare-ci-image
    outputs:
      image: ${{ needs.prepare-ci-image.outputs.image }}
    steps:
      - name: Check prepare-ci-image result
        run: |
          if [ "${{ needs.prepare-ci-image.result }}" != "success" ]; then
            echo "prepare-ci-image failed (result: ${{ needs.prepare-ci-image.result }}). Failing workflow-initialization job explicitly."
            exit 1
          fi
      - name: Set outputs
        run: |
          echo "image=${{ needs.prepare-ci-image.outputs.image }}" >> $GITHUB_OUTPUT

  rust:
    needs: workflow-initialization
    uses: ./.github/workflows/ci-rust.yml
    with:
      image: ${{ needs.workflow-initialization.outputs.image }}

  web:
    needs: workflow-initialization
    uses: ./.github/workflows/ci-web.yml
    with:
      image: ${{ needs.workflow-initialization.outputs.image }}

  docker:
    needs: workflow-initialization
    uses: ./.github/workflows/ci-docker.yml
    permissions:
      packages: write
    with:
      image: ${{ needs.workflow-initialization.outputs.image }}
      image-tags: ${{ github.event.pull_request.number && format('pr-{0}', github.event.pull_request.number) || 'latest' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call-security-audit:
    needs: workflow-initialization
    uses: ./.github/workflows/audit.yml
    with:
      image: ${{ needs.workflow-initialization.outputs.image }}
