# Build all Rust-generated web artifacts (typegen + wasm)
web-artifacts:
    cargo xtask

web-install:
    cd {{ source_directory() }} && npm install

web-clean:
    rm -rf \
        {{ source_directory() }}/generated \
        {{ source_directory() }}/build \
        {{ source_directory() }}/node_modules \
        {{ source_directory() }}/.svelte-kit \
        {{ source_directory() }}/../.pnpm-store

web-build: web-artifacts web-install
    cd {{ source_directory() }} && npm run build

web-lint: web-artifacts web-install
    cd {{ source_directory() }} && npm run lint

web-lint-fix: web-install
    cd {{ source_directory() }} && npm run lint:fix

web-format: web-install
    cd {{ source_directory() }} && npm run format

web-format-check: web-install
    cd {{ source_directory() }} && npm run format:check

web: web-build
    cd {{ source_directory() }} && npm run preview -- --host

web-dev: web-artifacts web-install
    cd {{ source_directory() }} && npm run dev -- --host
